//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/fluxcd/helm-controller/api/v2beta2"
	"github.com/fluxcd/source-controller/api/v1beta2"
	corev1 "k8s.io/api/core/v1"
	policyv1 "k8s.io/api/policy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRelease) DeepCopyInto(out *HelmRelease) {
	*out = *in
	if in.MarkedForDeletionAt != nil {
		in, out := &in.MarkedForDeletionAt, &out.MarkedForDeletionAt
		*out = new(string)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(v2beta2.HelmRelease)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRelease.
func (in *HelmRelease) DeepCopy() *HelmRelease {
	if in == nil {
		return nil
	}
	out := new(HelmRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmRepository) DeepCopyInto(out *HelmRepository) {
	*out = *in
	if in.MarkedForDeletionAt != nil {
		in, out := &in.MarkedForDeletionAt, &out.MarkedForDeletionAt
		*out = new(string)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(v1beta2.HelmRepository)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmRepository.
func (in *HelmRepository) DeepCopy() *HelmRepository {
	if in == nil {
		return nil
	}
	out := new(HelmRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(IngressType)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
	if in.NGINX != nil {
		in, out := &in.NGINX, &out.NGINX
		*out = new(NGINXConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Traefik != nil {
		in, out := &in.Traefik, &out.Traefik
		*out = new(TraefikConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesPod) DeepCopyInto(out *KubernetesPod) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesPod.
func (in *KubernetesPod) DeepCopy() *KubernetesPod {
	if in == nil {
		return nil
	}
	out := new(KubernetesPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesService) DeepCopyInto(out *KubernetesService) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesService.
func (in *KubernetesService) DeepCopy() *KubernetesService {
	if in == nil {
		return nil
	}
	out := new(KubernetesService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesStatefulSet) DeepCopyInto(out *KubernetesStatefulSet) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(KubernetesPod)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesStatefulSet.
func (in *KubernetesStatefulSet) DeepCopy() *KubernetesStatefulSet {
	if in == nil {
		return nil
	}
	out := new(KubernetesStatefulSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NGINXConfig) DeepCopyInto(out *NGINXConfig) {
	*out = *in
	if in.AllowedSourceRanges != nil {
		in, out := &in.AllowedSourceRanges, &out.AllowedSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GRPCHost != nil {
		in, out := &in.GRPCHost, &out.GRPCHost
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NGINXConfig.
func (in *NGINXConfig) DeepCopy() *NGINXConfig {
	if in == nil {
		return nil
	}
	out := new(NGINXConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = make(map[corev1.PodConditionType]corev1.ConditionStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operation) DeepCopyInto(out *Operation) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]OperationStep, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operation.
func (in *Operation) DeepCopy() *Operation {
	if in == nil {
		return nil
	}
	out := new(Operation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStep) DeepCopyInto(out *OperationStep) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStep.
func (in *OperationStep) DeepCopy() *OperationStep {
	if in == nil {
		return nil
	}
	out := new(OperationStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pause) DeepCopyInto(out *Pause) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pause.
func (in *Pause) DeepCopy() *Pause {
	if in == nil {
		return nil
	}
	out := new(Pause)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantCloudRegion) DeepCopyInto(out *QdrantCloudRegion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantCloudRegion.
func (in *QdrantCloudRegion) DeepCopy() *QdrantCloudRegion {
	if in == nil {
		return nil
	}
	out := new(QdrantCloudRegion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantCloudRegion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantCloudRegionList) DeepCopyInto(out *QdrantCloudRegionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantCloudRegion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantCloudRegionList.
func (in *QdrantCloudRegionList) DeepCopy() *QdrantCloudRegionList {
	if in == nil {
		return nil
	}
	out := new(QdrantCloudRegionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantCloudRegionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantCloudRegionSpec) DeepCopyInto(out *QdrantCloudRegionSpec) {
	*out = *in
	if in.HelmRepositories != nil {
		in, out := &in.HelmRepositories, &out.HelmRepositories
		*out = make([]HelmRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HelmReleases != nil {
		in, out := &in.HelmReleases, &out.HelmReleases
		*out = make([]HelmRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantCloudRegionSpec.
func (in *QdrantCloudRegionSpec) DeepCopy() *QdrantCloudRegionSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantCloudRegionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantCloudRegionStatus) DeepCopyInto(out *QdrantCloudRegionStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(RegionCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.HelmRepositories != nil {
		in, out := &in.HelmRepositories, &out.HelmRepositories
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
	if in.HelmReleases != nil {
		in, out := &in.HelmReleases, &out.HelmReleases
		*out = make([]ComponentStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantCloudRegionStatus.
func (in *QdrantCloudRegionStatus) DeepCopy() *QdrantCloudRegionStatus {
	if in == nil {
		return nil
	}
	out := new(QdrantCloudRegionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantCluster) DeepCopyInto(out *QdrantCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantCluster.
func (in *QdrantCluster) DeepCopy() *QdrantCluster {
	if in == nil {
		return nil
	}
	out := new(QdrantCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterList) DeepCopyInto(out *QdrantClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterList.
func (in *QdrantClusterList) DeepCopy() *QdrantClusterList {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRestore) DeepCopyInto(out *QdrantClusterRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRestore.
func (in *QdrantClusterRestore) DeepCopy() *QdrantClusterRestore {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRestoreList) DeepCopyInto(out *QdrantClusterRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantClusterRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRestoreList.
func (in *QdrantClusterRestoreList) DeepCopy() *QdrantClusterRestoreList {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRestoreSpec) DeepCopyInto(out *QdrantClusterRestoreSpec) {
	*out = *in
	out.Source = in.Source
	out.Destination = in.Destination
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRestoreSpec.
func (in *QdrantClusterRestoreSpec) DeepCopy() *QdrantClusterRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRestoreStatus) DeepCopyInto(out *QdrantClusterRestoreStatus) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRestoreStatus.
func (in *QdrantClusterRestoreStatus) DeepCopy() *QdrantClusterRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterScheduledSnapshot) DeepCopyInto(out *QdrantClusterScheduledSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterScheduledSnapshot.
func (in *QdrantClusterScheduledSnapshot) DeepCopy() *QdrantClusterScheduledSnapshot {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterScheduledSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterScheduledSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterScheduledSnapshotList) DeepCopyInto(out *QdrantClusterScheduledSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantClusterScheduledSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterScheduledSnapshotList.
func (in *QdrantClusterScheduledSnapshotList) DeepCopy() *QdrantClusterScheduledSnapshotList {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterScheduledSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterScheduledSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterScheduledSnapshotSpec) DeepCopyInto(out *QdrantClusterScheduledSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterScheduledSnapshotSpec.
func (in *QdrantClusterScheduledSnapshotSpec) DeepCopy() *QdrantClusterScheduledSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterScheduledSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterScheduledSnapshotStatus) DeepCopyInto(out *QdrantClusterScheduledSnapshotStatus) {
	*out = *in
	in.Scheduled.DeepCopyInto(&out.Scheduled)
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterScheduledSnapshotStatus.
func (in *QdrantClusterScheduledSnapshotStatus) DeepCopy() *QdrantClusterScheduledSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterScheduledSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterSnapshot) DeepCopyInto(out *QdrantClusterSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterSnapshot.
func (in *QdrantClusterSnapshot) DeepCopy() *QdrantClusterSnapshot {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterSnapshotList) DeepCopyInto(out *QdrantClusterSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantClusterSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterSnapshotList.
func (in *QdrantClusterSnapshotList) DeepCopy() *QdrantClusterSnapshotList {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterSnapshotSpec) DeepCopyInto(out *QdrantClusterSnapshotSpec) {
	*out = *in
	if in.ScheduleShortId != nil {
		in, out := &in.ScheduleShortId, &out.ScheduleShortId
		*out = new(string)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterSnapshotSpec.
func (in *QdrantClusterSnapshotSpec) DeepCopy() *QdrantClusterSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterSnapshotStatus) DeepCopyInto(out *QdrantClusterSnapshotStatus) {
	*out = *in
	if in.VolumeSnapshots != nil {
		in, out := &in.VolumeSnapshots, &out.VolumeSnapshots
		*out = make([]VolumeSnapshotInfo, len(*in))
		copy(*out, *in)
	}
	if in.RetainUntil != nil {
		in, out := &in.RetainUntil, &out.RetainUntil
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterSnapshotStatus.
func (in *QdrantClusterSnapshotStatus) DeepCopy() *QdrantClusterSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterSpec) DeepCopyInto(out *QdrantClusterSpec) {
	*out = *in
	if in.ClusterManager != nil {
		in, out := &in.ClusterManager, &out.ClusterManager
		*out = new(bool)
		**out = **in
	}
	if in.Pauses != nil {
		in, out := &in.Pauses, &out.Pauses
		*out = make([]Pause, len(*in))
		copy(*out, *in)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(QdrantImage)
		(*in).DeepCopyInto(*out)
	}
	out.Resources = in.Resources
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(QdrantSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(QdrantConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(Ingress)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(KubernetesService)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(KubernetesStatefulSet)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClassNames != nil {
		in, out := &in.StorageClassNames, &out.StorageClassNames
		*out = new(StorageClassNames)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = new([]corev1.TopologySpreadConstraint)
		if **in != nil {
			in, out := *in, *out
			*out = make([]corev1.TopologySpreadConstraint, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(policyv1.PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterSpec.
func (in *QdrantClusterSpec) DeepCopy() *QdrantClusterSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterStatus) DeepCopyInto(out *QdrantClusterStatus) {
	*out = *in
	if in.AvailableNodeIndexes != nil {
		in, out := &in.AvailableNodeIndexes, &out.AvailableNodeIndexes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.DeleteInProgessNodeIndexes != nil {
		in, out := &in.DeleteInProgessNodeIndexes, &out.DeleteInProgessNodeIndexes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ScaleDownNodeIndex != nil {
		in, out := &in.ScaleDownNodeIndex, &out.ScaleDownNodeIndex
		*out = new(int)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]Operation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	in.NextClusterManagerInvocation.DeepCopyInto(&out.NextClusterManagerInvocation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterStatus.
func (in *QdrantClusterStatus) DeepCopy() *QdrantClusterStatus {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantConfiguration) DeepCopyInto(out *QdrantConfiguration) {
	*out = *in
	if in.Collection != nil {
		in, out := &in.Collection, &out.Collection
		*out = new(QdrantConfigurationCollection)
		(*in).DeepCopyInto(*out)
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(QdrantConfigurationService)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(QdrantConfigurationTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantConfiguration.
func (in *QdrantConfiguration) DeepCopy() *QdrantConfiguration {
	if in == nil {
		return nil
	}
	out := new(QdrantConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantConfigurationCollection) DeepCopyInto(out *QdrantConfigurationCollection) {
	*out = *in
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(int64)
		**out = **in
	}
	if in.WriteConsistencyFactor != nil {
		in, out := &in.WriteConsistencyFactor, &out.WriteConsistencyFactor
		*out = new(int64)
		**out = **in
	}
	if in.Vectors != nil {
		in, out := &in.Vectors, &out.Vectors
		*out = new(QdrantConfigurationCollectionVectors)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantConfigurationCollection.
func (in *QdrantConfigurationCollection) DeepCopy() *QdrantConfigurationCollection {
	if in == nil {
		return nil
	}
	out := new(QdrantConfigurationCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantConfigurationCollectionVectors) DeepCopyInto(out *QdrantConfigurationCollectionVectors) {
	*out = *in
	if in.OnDisk != nil {
		in, out := &in.OnDisk, &out.OnDisk
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantConfigurationCollectionVectors.
func (in *QdrantConfigurationCollectionVectors) DeepCopy() *QdrantConfigurationCollectionVectors {
	if in == nil {
		return nil
	}
	out := new(QdrantConfigurationCollectionVectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantConfigurationService) DeepCopyInto(out *QdrantConfigurationService) {
	*out = *in
	if in.ApiKey != nil {
		in, out := &in.ApiKey, &out.ApiKey
		*out = new(QdrantSecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnlyApiKey != nil {
		in, out := &in.ReadOnlyApiKey, &out.ReadOnlyApiKey
		*out = new(QdrantSecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
	if in.JwtRbac != nil {
		in, out := &in.JwtRbac, &out.JwtRbac
		*out = new(bool)
		**out = **in
	}
	if in.EnableTLS != nil {
		in, out := &in.EnableTLS, &out.EnableTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantConfigurationService.
func (in *QdrantConfigurationService) DeepCopy() *QdrantConfigurationService {
	if in == nil {
		return nil
	}
	out := new(QdrantConfigurationService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantConfigurationTLS) DeepCopyInto(out *QdrantConfigurationTLS) {
	*out = *in
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(QdrantSecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(QdrantSecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantConfigurationTLS.
func (in *QdrantConfigurationTLS) DeepCopy() *QdrantConfigurationTLS {
	if in == nil {
		return nil
	}
	out := new(QdrantConfigurationTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantImage) DeepCopyInto(out *QdrantImage) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.PullPolicy != nil {
		in, out := &in.PullPolicy, &out.PullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
	if in.PullSecretName != nil {
		in, out := &in.PullSecretName, &out.PullSecretName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantImage.
func (in *QdrantImage) DeepCopy() *QdrantImage {
	if in == nil {
		return nil
	}
	out := new(QdrantImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantRelease) DeepCopyInto(out *QdrantRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantRelease.
func (in *QdrantRelease) DeepCopy() *QdrantRelease {
	if in == nil {
		return nil
	}
	out := new(QdrantRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantReleaseList) DeepCopyInto(out *QdrantReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantReleaseList.
func (in *QdrantReleaseList) DeepCopy() *QdrantReleaseList {
	if in == nil {
		return nil
	}
	out := new(QdrantReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantReleaseSpec) DeepCopyInto(out *QdrantReleaseSpec) {
	*out = *in
	if in.AccountIDs != nil {
		in, out := &in.AccountIDs, &out.AccountIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccountPrivileges != nil {
		in, out := &in.AccountPrivileges, &out.AccountPrivileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantReleaseSpec.
func (in *QdrantReleaseSpec) DeepCopy() *QdrantReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantSecretKeyRef) DeepCopyInto(out *QdrantSecretKeyRef) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantSecretKeyRef.
func (in *QdrantSecretKeyRef) DeepCopy() *QdrantSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(QdrantSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantSecurityContext) DeepCopyInto(out *QdrantSecurityContext) {
	*out = *in
	if in.FsGroup != nil {
		in, out := &in.FsGroup, &out.FsGroup
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantSecurityContext.
func (in *QdrantSecurityContext) DeepCopy() *QdrantSecurityContext {
	if in == nil {
		return nil
	}
	out := new(QdrantSecurityContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionCapabilities) DeepCopyInto(out *RegionCapabilities) {
	*out = *in
	if in.VolumeSnapshot != nil {
		in, out := &in.VolumeSnapshot, &out.VolumeSnapshot
		*out = new(bool)
		**out = **in
	}
	if in.VolumeExpansion != nil {
		in, out := &in.VolumeExpansion, &out.VolumeExpansion
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionCapabilities.
func (in *RegionCapabilities) DeepCopy() *RegionCapabilities {
	if in == nil {
		return nil
	}
	out := new(RegionCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequests) DeepCopyInto(out *ResourceRequests) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequests.
func (in *ResourceRequests) DeepCopy() *ResourceRequests {
	if in == nil {
		return nil
	}
	out := new(ResourceRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	out.Requests = in.Requests
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreDestination) DeepCopyInto(out *RestoreDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreDestination.
func (in *RestoreDestination) DeepCopy() *RestoreDestination {
	if in == nil {
		return nil
	}
	out := new(RestoreDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSource) DeepCopyInto(out *RestoreSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSource.
func (in *RestoreSource) DeepCopy() *RestoreSource {
	if in == nil {
		return nil
	}
	out := new(RestoreSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassNames) DeepCopyInto(out *StorageClassNames) {
	*out = *in
	if in.DB != nil {
		in, out := &in.DB, &out.DB
		*out = new(string)
		**out = **in
	}
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassNames.
func (in *StorageClassNames) DeepCopy() *StorageClassNames {
	if in == nil {
		return nil
	}
	out := new(StorageClassNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.AsyncScorer != nil {
		in, out := &in.AsyncScorer, &out.AsyncScorer
		*out = new(bool)
		**out = **in
	}
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(StoragePerformanceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePerformanceConfig) DeepCopyInto(out *StoragePerformanceConfig) {
	*out = *in
	if in.OptimizerCPUBudget != nil {
		in, out := &in.OptimizerCPUBudget, &out.OptimizerCPUBudget
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePerformanceConfig.
func (in *StoragePerformanceConfig) DeepCopy() *StoragePerformanceConfig {
	if in == nil {
		return nil
	}
	out := new(StoragePerformanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraefikConfig) DeepCopyInto(out *TraefikConfig) {
	*out = *in
	if in.AllowedSourceRanges != nil {
		in, out := &in.AllowedSourceRanges, &out.AllowedSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraefikConfig.
func (in *TraefikConfig) DeepCopy() *TraefikConfig {
	if in == nil {
		return nil
	}
	out := new(TraefikConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSnapshotInfo) DeepCopyInto(out *VolumeSnapshotInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSnapshotInfo.
func (in *VolumeSnapshotInfo) DeepCopy() *VolumeSnapshotInfo {
	if in == nil {
		return nil
	}
	out := new(VolumeSnapshotInfo)
	in.DeepCopyInto(out)
	return out
}
