//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapStatusInfo) DeepCopyInto(out *BootstrapStatusInfo) {
	*out = *in
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = new(bool)
		**out = **in
	}
	if in.Dedicated != nil {
		in, out := &in.Dedicated, &out.Dedicated
		*out = new(bool)
		**out = **in
	}
	if in.Bootstrapped != nil {
		in, out := &in.Bootstrapped, &out.Bootstrapped
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapStatusInfo.
func (in *BootstrapStatusInfo) DeepCopy() *BootstrapStatusInfo {
	if in == nil {
		return nil
	}
	out := new(BootstrapStatusInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRouting) DeepCopyInto(out *QdrantClusterRouting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRouting.
func (in *QdrantClusterRouting) DeepCopy() *QdrantClusterRouting {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterRouting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRoutingList) DeepCopyInto(out *QdrantClusterRoutingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QdrantClusterRouting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRoutingList.
func (in *QdrantClusterRoutingList) DeepCopy() *QdrantClusterRoutingList {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRoutingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QdrantClusterRoutingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRoutingSpec) DeepCopyInto(out *QdrantClusterRoutingSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Shared != nil {
		in, out := &in.Shared, &out.Shared
		*out = new(bool)
		**out = **in
	}
	if in.Dedicated != nil {
		in, out := &in.Dedicated, &out.Dedicated
		*out = new(bool)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
	if in.ServicePerNode != nil {
		in, out := &in.ServicePerNode, &out.ServicePerNode
		*out = new(bool)
		**out = **in
	}
	if in.NodeIndexes != nil {
		in, out := &in.NodeIndexes, &out.NodeIndexes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSourceRanges != nil {
		in, out := &in.AllowedSourceRanges, &out.AllowedSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableAccessLog != nil {
		in, out := &in.EnableAccessLog, &out.EnableAccessLog
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRoutingSpec.
func (in *QdrantClusterRoutingSpec) DeepCopy() *QdrantClusterRoutingSpec {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantClusterRoutingStatus) DeepCopyInto(out *QdrantClusterRoutingStatus) {
	*out = *in
	if in.Bootstrapped != nil {
		in, out := &in.Bootstrapped, &out.Bootstrapped
		*out = new(bool)
		**out = **in
	}
	if in.BootstrapInfos != nil {
		in, out := &in.BootstrapInfos, &out.BootstrapInfos
		*out = new([]BootstrapStatusInfo)
		if **in != nil {
			in, out := *in, *out
			*out = make([]BootstrapStatusInfo, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantClusterRoutingStatus.
func (in *QdrantClusterRoutingStatus) DeepCopy() *QdrantClusterRoutingStatus {
	if in == nil {
		return nil
	}
	out := new(QdrantClusterRoutingStatus)
	in.DeepCopyInto(out)
	return out
}
